### ISSUE TITLE
[Issue] Twitch sub bug 

### ISSUE THREAD

**Issue by shipofgenius** [TalimaVale/BeastieBot#18]
Currently a subscription is sent via PRIVMSG in IRC twice. Once when the viewer immediately subscribes and a second time when they click the share on the twitch site. This is currently breaking bots who are not tracking their subs locally. Beastiebot should correct for this.

**Comment by TalimaVale** [comment]
Thanks for pointing this out! We'll keep this in mind when we start working on the overlay/alerts.
