### ISSUE TITLE
Interval for Hydration Reminder

### ISSUE THREAD

**Issue by benwurth** [TalimaVale/BeastieBot#2]
The comments in the code in index.js at line 175 say that the hydration timer is supposed to be set for 28 minutes, but the code will actually repeat the function every 1 minute.

Either the timer needs to change, or the comment is wrong

(This issue was originally posted accidentally on the teamTALIMA_theGAME repo)

**Comment by TalimaVale** [comment]
Thanks for catching this! Code was set to 1min locally (and uploaded to repo) yet 28min on the server so I didn't see that. :P
