### ISSUE TITLE
[ISSUE] Error Handling when checking for follows

### ISSUE THREAD

**Issue by shipofgenius** [TalimaVale/BeastieBot#29]
```
 There was a problem querying the Twitch API for follows:
{ Error: connect EACCES 54.148.125.194:443
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'connect',
  address: '54.148.125.194',
  port: 443 }
```

Its not happening every call, so its probably just a periodic connection issue and bad timing. What about:
 if it cant connect, pause X seconds and try again. Go back to regular timer upon success.

**Comment by TalimaVale** [comment]
Solved! Really good idea with the pause-retry feature, but I'm hoping we completely solved Beastie's periodic with our recent changes. Thanks!
