### ISSUE TITLE
Raid bonus is dispensed 2 minutes after every autohost "hosting" event.

### ISSUE THREAD

**Issue by scryptonite** [TalimaVale/BeastieBot#7]
When the broadcaster channel automatically hosts another channel after a raid was started during the prior stream, Beastie will erroneously dispense bonus awesomeness as though each hosting event was a sign of a intentional raid on that channel.

Here's a screenshot of Beastie running the `!bonusall` command after every autohost that occurred after last night's legitimate raid on SoMuchMonsters:

![](https://cloud.githubusercontent.com/assets/905015/26169166/8d2499cc-3af1-11e7-8a9c-f41d2a74648b.png)

In the above screenshot we can see that Beastie decided to emit two raid bonuses. This is probably because the "hosting" event was fired multiple times. 
As to why he didn't say "Time to raid! :D rawr" twice, I think this is because Twitch silenced the same message from being duplicate posted in such a short timeframe.

The next autohost did not fire multiple "hosting" events though, so it must be somewhat rare: 

![](https://cloud.githubusercontent.com/assets/905015/26169497/b8238222-3af2-11e7-9ae8-e1660a962d41.png)

<br><br>

I have created a branch called [`scryptonite-patch-raids`][scryptonite-patch-raids] to address fixing the raid logic.
  - ✔️ When the raid bonus is handed out, Beastie is no longer in raid mode.
  - ⚠️ Refactored all of the raid logic into /commands/raid.js; I think this is more tidy and easier to parse, but I want to get your thoughts on whether you approve before submitting a PR. @teamTALIMA 

[scryptonite-patch-raids]: https://github.com/scryptonite/BeastieBot/tree/scryptonite-patch-raids

**Comment by TalimaVale** [comment]
Accepted your [`scryptonite-patch-raids`](https://github.com/scryptonite/BeastieBot/tree/scryptonite-patch-raids )! Thank you!
